

INSERT INTO TODO (ID,USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1011,'Ashir', 'Get AWS Certified', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID,USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1012,'Ashir', 'Get AZURE Certified', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID,USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1013,'Ashir', 'Learn Spring boot ', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID,USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1014,'Ashir', 'Get first programming job', CURRENT_DATE, FALSE);